modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/ochotonida/curious-armor-stands/issues"

[[mods]]
modId="curious_armor_stands"
version="1.16.1-1.0.0"
displayName="Curious Armor Stands"
displayURL="https://www.curseforge.com/minecraft/mc-mods/curious-armor-stands"
# todo logoFile="examplemod.png" A file name (in the root of the mod JAR) containing a logo for display
description='''Allows armor stands to wear curios'''

[[dependencies.curious_armor_stands]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.curious_armor_stands]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.curious_armor_stands]]
    modId="curios"
    mandatory=true
    versionRange="[FORGE-1.16.1-3.0,)"
    ordering="AFTER"
    side="BOTH"